### ISSUE TITLE
doesn't works with Leaflet 0.7.7

### ISSUE THREAD

**Issue by Hippipers** [MarcChasse/leaflet.ScaleFactor#6]
With Leaflet 0.7.7, console returns "leaflet.scalefactor.min.js:5 Uncaught TypeError: e.distance is not a function"

**Comment by Hippipers** [comment]
Ok, I've replaced 

var RealWorlMetersPer100Pixels = map.distance(
                map.containerPointToLatLng([0, CenterOfMap]),
                map.containerPointToLatLng([100, CenterOfMap])
            );
by

var RealWorlMetersPer100Pixels = (
                map.containerPointToLatLng([0, CenterOfMap]).distanceTo(
                map.containerPointToLatLng([100, CenterOfMap]))
            );

And now it works
